# Brand Listener Configuration
brand:
  handles: ["Send"]  # Twitter handles to monitor for mentions
  keywords: ["#sendit"]  # Keywords to search for

filters:
  lang: "en"  # Language filter for tweets
  time_range_hours: 2 # How many hours back to search (start small for testing)

notify:
  slack_channel: "#social"  # Slack channel for notifications

thresholds:
  notify: 0.80  # Relevance score needed for Slack notifications
  log_only: 0.60  # Relevance score needed for logging to sheets

sheet:
  spreadsheetId: "1FWXaMfO0p_LEdsjDT1YVaokq2MAndeLfDStuGCLUizY"
  sheetName: "Sheet1"
