# Brand Listener Configuration - Example
# Replace these with your actual brand information

brand:
  handles: ["yourbrand", "yourcompany"]  # Twitter handles to monitor (without @)
  keywords: ["your product", "your service", "your company"]  # Keywords to search for

filters:
  lang: "en"  # Language filter for tweets
  time_range_hours: 6  # How many hours back to search (start with 2-6 for testing)

notify:
  slack_channel: "#social-monitoring"  # Slack channel for notifications

thresholds:
  notify: 0.80  # Relevance score needed for Slack notifications (0.0-1.0)
  log_only: 0.60  # Relevance score needed for logging to sheets (0.0-1.0)

sheet:
  spreadsheetId: "YOUR_GOOGLE_SHEET_ID_HERE"  # Replace with your Google Sheet ID
  sheetName: "Sheet1"
